Feature/sprints test
chingu-x/chingu-dashboard-be pull request #113
Opened 2024-03-08 05:18 UTC by JoshuaHinman

# Description

- Added tests for all sprints routes
- Added `jest-extended` dependency to provide `expect.toBeOneOf()` and other useful functions

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [x] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

yarn test:e2e sprints

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

2024-03-08 12:29 UTC, cherylli reviewed
Very thorough tests, all passed locally here. thanks!
just need to resolve that changelog conflict

2024-03-08 12:39 UTC, siasktv submitted a review, later dismissed

2024-03-08 12:39 UTC, siasktv commented on CHANGELOG.md
> +- Add e2e tests for sprint controller
Wow very well structured tests. The only thing I see missing I guess in the changelog would be the url? Otherwise I have no comments

2024-03-08 15:49 UTC, timDeHof requested changes
very good structured tests but maybe label the test suites and specs to convey clearer intention of each unit test. I have added some suggestions for the `describe` and `it` blocks. I think it would make it easier for new developers to understand the intention of the unit tests.

I found this [unit testing style guide](https://github.com/nikeshghimire77/unit-testing-styleguide) that could help us keep a consist style to the tests.

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("    verify sprint meeting in database", async () => {
```suggestion
describe("verifies sprint meeting updated in database", () => {
        it("shows updated sprint meeting from database", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 409 - Tried to create meeting, one already exists for this sprint", async () => {
```suggestion
        it("should return 409 if a sprint meeting already exists for this sprint", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 404 - Resource (team Id) not found", async () => {
```suggestion
        it("should return 404 if team Id is not found", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 400 - Bad request", async () => {
```suggestion
        it("should return 400 if title isn't a string", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 201 - New agenda added", async () => {
```suggestion
    describe("creates a new meeting agenda POST /voyages/sprints/meetings/:meetingId/agendas", () => {
        it("should return 201 when new agenda is added", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("    verify new agenda in database", async () => {
```suggestion
describe("verifies that a new agenda is in the database", (0 => {
        it("shows new agenda from database", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 400 - Bad Request - Invalid Meeting Id", async () => {
```suggestion
        it("should return 400 if Meeting Id is invalid", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("PATCH 200 - Agenda updated successfully", async () => {
```suggestion
    describe("updates agenda PATCH /voyages/sprints/agendas/:agendaId", () => {
        it("should return 200 if Agenda was updated successfully", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("    verify patch in database", async () => {
```suggestion
describe("verifies that an agenda was updated in database", () => {
        it("shows updated agenda from database", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("PATCH 404 - Invalid Agenda Id", async () => {
```suggestion
        it("should return 404 if Agenda Id is invalid", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 200 - Meeting form created successfully", async () => {
```suggestion
    describe("create a meeting form POST /voyages/sprints/meetings/:meetingId/forms/:formId", () => {
        it("should return 200 if Meeting form creation was successful", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("POST 409 - Form already exists for this meeting", async () => {
```suggestion
        it("should return 409 if Form exists for this meeting", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("GET 200 - Successfully get the meeting form with responses", async () => {
```suggestion
describe("get meeting form GET /voyages/sprints/meetings/${meetingId}/forms/${formId}", () => {
        it("should return 200 and the meeting form if successful", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("GET 404 - Invalid meeting", async () => {
```suggestion
        it("should return 404 if meeting id is invalid", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("GET 400 - Invalid form", async () => {
```suggestion
        it("should return 400 if meeting id is correct but form id is invalid", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("PATCH 200 - Successfully update the meeting form with responses", async () => {
```suggestion
describe("updates meeting form PATCH /voyages/sprints/meetings/${meetingId}/forms/${formId}", () => {
        it("should return 200 if update to the meeting form was successful", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("    verify meeting response in database", async () => {
```suggestion
describe("verifies that meeting was updated in database", () => {
        it("shows response in updated meeting from database", async () => {
```

2024-03-08 15:49 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("PATCH 400 - Bad request", async () => {
```suggestion
        it("should return 400 if form id is a string", async () => {
```

2024-03-08 20:38 UTC, cherylli commented on test/sprints.e2e-spec.ts
> +        it("GET - 200 successfully gets all voyage and sprints data", async () => {
I think we should keep the GET, and 200 in the it description

2024-03-11 00:54 UTC, JoshuaHinman commented on test/sprints.e2e-spec.ts
These are great suggestions - thanks for the feedback!

2024-03-13 20:38 UTC, JoshuaHinman commented
Revisions:
- Tests are grouped in describe blocks labelled by METHOD and /route
- Successful responses shown as '20x - should...'
- Database tests shown as 'verify ... in database'
- Others shown as 'should return 40X if...'
- Added, revised some tests

2024-03-13 20:50 UTC, JoshuaHinman reviewed
done

2024-03-14 02:19 UTC, cherylli requested changes
everything looks good, just need a minor adjustment in the changelog 🙌

2024-03-14 03:32 UTC, cherylli approved these changes
thank you!

2024-03-15 03:34 UTC, cherylli approved these changes

2024-03-15 15:45 UTC, timDeHof commented on test/sprints.e2e-spec.ts
> +        it("200 - should return all the sprint dates of a particular team", async () => {
```suggestion
        it("should return 200 and all the sprint dates of a particular team", async () => {
```

2024-03-15 16:04 UTC, timDeHof submitted a review, later dismissed
It's looking great. I have spotted a couple of `it` statements that could be written in a way that newcomers could understand the tests better.

2024-03-16 03:28 UTC, cherylli approved these changes

2024-03-17 00:10 UTC, curtwl approved these changes
Looks good!

2024-03-17 17:20 UTC, merged