Feature: sprint checkin form submission status for user
chingu-x/chingu-dashboard-be pull request #149
Opened 2024-05-08 05:52 UTC by Ajen07

# Description

added check in submission status in the response, the sprintId will be in sprintCheckin list if the user has submitted a check in form for the sprint

## Issue link
[
Fixes # (issue)](https://app.clickup.com/t/86b00h4gx)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- unit tests
![unit-test-passed](https://github.com/chingu-x/chingu-dashboard-be/assets/112967686/9c137de4-37dc-4dee-89ad-c7768473db23)

- e2e tests
![e2e-test-passed](https://github.com/chingu-x/chingu-dashboard-be/assets/112967686/a49b7c29-8ea6-4820-9c50-0f82265f6461)

- swagger
![swaager](https://github.com/chingu-x/chingu-dashboard-be/assets/112967686/3b884f08-6fa6-4973-8b7c-d774e6283254)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

2024-05-08 06:12 UTC, cherylli reviewed
edit: move to review comment

2024-05-08 06:22 UTC, cherylli requested changes
we shouldn't need to add any field to the table, we can retrieve the data without added another field to the table

you can retrieve the data from sprint check in table and append it to the /me endpoint

we don't want to add extra/unnecessary columns to tables, we need to make use of the relations

I guess one thing to keep in mind is we don't want to create duplicate data just for the purpose of retrieval.

====
So to reiterate,

in the fetch user detail endpoint `users/me`,

fetch the users voyageTeamMemberId, use this id to query sprintCheckin table, append this data to the response, so something like this

```ts
prisma.FormResponseCheckin.findMany({
where: voyageTeamMemberId {
id: { in: voyageTeamMemberId}
}, seleect:{
  sprintId: true
}
```

where voyageTeamMemberId is the list of Id from the user table


![image](https://github.com/chingu-x/chingu-dashboard-be/assets/6191116/0b93d9d8-1a47-4b4b-8037-b13aa772b34c)

2024-05-10 22:51 UTC, JoshuaHinman approved these changes
Tests passed and checkins displayed in response - nice job!  It would have been helpful for the users/me route to be identified in the Description or Tested section - at first I assumed it was the sprints/checkin route

2024-05-10 23:44 UTC, cherylli requested changes

2024-05-10 23:45 UTC, cherylli commented
sorry I forgot to submit my reviews which I did a couple of days ago, so they were pending

2024-05-11 03:35 UTC, Ajen07 commented on prisma/migrations/20240507131015_add_sprint_checkin_for_user/migration.sql
Actually all my up migrations are in a single commit but the down migration and other changes are in a single commit.So is there any way I can remove both the migration file ?

2024-05-11 03:37 UTC, Ajen07 commented
> Tests passed and checkins displayed in response - nice job! It would have been helpful for the users/me route to be identified in the Description or Tested section - at first I assumed it was the sprints/checkin route

Got it ! .From the next time , I will make my descriptions more elaborative about the issue and its solutions .

2024-05-11 03:40 UTC, cherylli commented on prisma/migrations/20240507131015_add_sprint_checkin_for_user/migration.sql
I think you can just delete both migration folders locally and commit then they won't show in the changes

2024-05-11 04:28 UTC, Ajen07 commented on prisma/migrations/20240507131015_add_sprint_checkin_for_user/migration.sql
Ok I will delete them locally and push the changes.

2024-05-11 15:14 UTC, cherylli approved these changes

2024-05-14 02:28 UTC, timDeHof approved these changes
Great job! All tests passes and swagger endpoint responses with a 201.

2024-05-14 03:05 UTC, merged