Test: unit tests for Team resources
chingu-x/chingu-dashboard-be pull request #201
Opened 2024-09-16 11:12 UTC by Ajen07

# Description

- Unit test for Team Resource services and controller

## Issue link

[Fixes # (issue)](https://app.clickup.com/t/86azu6kwr)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [x] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- test with `yarn test:docker`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

2024-09-17 01:15 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +    };
Extract the mock objects and variables to a section above the describe in the test file. This will help in read ability of the tests.

2024-09-17 01:18 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                9999,
extract magic numbers like this one (9999) into constants for better readability.

2024-09-17 01:18 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                9999,
another magic number

2024-09-17 01:19 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                9999,
another magic number

2024-09-17 01:19 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                1,
another magic number

2024-09-17 01:19 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                9999,
another magic number

2024-09-17 01:22 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +    };
```suggestion
    const mockUpdatedResource = {
        ...mockResource,
        url: "https://chingu-2.com",
    };
```

2024-09-17 01:30 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +            ).rejects.toThrow(BadRequestException);
```suggestion
           await expect(
                controller.createNewResource(requestMock, mockTeamId, {
                    url: "https://chingu.com",
                } as CreateResourceDto),
            ).rejects.toThrow(BadRequestException);
```

2024-09-17 01:33 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +            ).rejects.toThrow(NotFoundException);
```suggestion
           await expect(
                controller.findAllResources(requestMock, 9999),
            ).rejects.toThrow(NotFoundException);
```

2024-09-17 01:34 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                1,
```suggestion
                mockResource.id,
```

2024-09-17 01:36 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                1,
try not to use magic numbers
```suggestion
                mockResource,id,
```

2024-09-17 01:37 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +            ).rejects.toThrow(NotFoundException);
```suggestion
            await expect(
                controller.updateResource(requestMock, 9999, dtoUpdateMock),
            ).rejects.toThrow(NotFoundException);
```

2024-09-17 01:39 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +                1,
try not to use magic numbers
```suggestion
                mockResource.id,
```

2024-09-17 01:39 UTC, timDeHof commented on src/resources/resources.controller.spec.ts
> +            ).rejects.toThrow(NotFoundException);
```suggestion
            await expect(
                controller.removeResource(requestMock, 9999),
            ).rejects.toThrow(NotFoundException);
```

2024-09-17 01:46 UTC, timDeHof commented on src/resources/resources.service.spec.ts
> +    ];
Extract the mock objects and variables to a section above the `describe` in the test file. This will help with the readability of the tests.

2024-09-17 01:49 UTC, timDeHof commented on src/resources/resources.service.spec.ts
> +    };
```suggestion
    const mockUpdatedResource = {
     ...mockResource,
     url: "https://chingu-2.com",
    };
```

2024-09-17 01:55 UTC, timDeHof commented on src/resources/resources.service.spec.ts
> +    });
maybe add a test for error cases
```suggestion
 it("should throw error if voyage team not found", async () => {
 	prismaMock.voyageTeam.findUnique.mockResolvedValue(null);

            await expect(service.createNewResource(requestMock, dtoCreateMock, mockTeamId)).rejects.toThrow();
 })
    });
```

2024-09-17 01:57 UTC, timDeHof commented on src/resources/resources.service.spec.ts
> +            expect(result[0]).toEqual({
test array length is correct
```suggestion
            expect(result).toHaveLength(2);
            expect(result[0]).toEqual({
```

2024-09-17 01:59 UTC, timDeHof commented on src/resources/resources.service.spec.ts
> +    });
add a test for error cases
```suggestion
        it("should throw error if voyage team not found", async () => {
            prismaMock.voyageTeam.findUnique.mockResolvedValue(null);

            await expect(service.findAllResources(requestMock, mockTeamId)).rejects.toThrow();
        });
    });
```

2024-09-17 02:05 UTC, timDeHof requested changes
all the tests passed but I added some suggestions for both unit tests that would help with the readability and maintainability of your tests.

2024-09-18 11:35 UTC, cherylli approved these changes
looks pretty good! All tests passed locally for me

2024-09-19 02:42 UTC, timDeHof approved these changes
All the tests passed. Thank you for making the changes! it looks great!

2024-09-19 03:05 UTC, merged