chore: update user voyage roles in dev seed
chingu-x/chingu-dashboard-be pull request #206
Opened 2024-09-21 13:06 UTC by Ajen07

# Description

- Created `4 new users`
- Updated team `v48-tier1-team-1`  to have    `1 UI/UX designer`  and  `1 data scientist`  having `memberId `as `9` and `10`
- Updated team `v48-tier3-team-30`  to have  all roles `1 SM`, `1 PO`,` 3 developers`, `1 UI/UX designer` , `1 data scientist`  and `1 voyage guide` having `memberId `as  `11`  , `12`, `13`, `14`, `15`, `16`, `17` and `18`
- Updated tema `v50-tier3-team-30` to have no `SM/PO` and only `3 developers` with `memberId`  `31`, `32` and `33`
- Updated team `v51-tier1-team-1` to have only `SM`  with `member Id`  `34`, `35` and `36`
- Updated team `v51-tier3-team-30` to have only `PO` with `memberId`  `37`, `38` and `39`

## Issue link

[Fixes # (issue)](https://app.clickup.com/t/86b27xvk2)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

- tested with `yarn seed`
- tested with `yarn test:docker`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

2024-09-21 13:22 UTC, cherylli reviewed
I think it's easier if all the teams with different composition is in the same voyage, so we don't have to manually overwrite the dates to check, but I need to check if frontend can handle that first.

2024-09-21 13:26 UTC, Ajen07 commented
> I think it's easier if all the teams with different composition is in the same voyage, so we don't have to manually overwrite the dates to check, but I need to check if frontend can handle that first.

In that case we will have people  belonging to different teams in the same voyage

2024-09-21 13:53 UTC, cherylli commented
> > I think it's easier if all the teams with different composition is in the same voyage, so we don't have to manually overwrite the dates to check, but I need to check if frontend can handle that first.
> 
> In that case we will have same people belonging to different teams in the same voyage or we have to create more users.

yes I prefer just using the same members, so we don't have to create too many, but lets see what frontend says. Eventually they will have to handle this situation, but I don't know if the current frontend can handle it yet

2024-09-22 00:10 UTC, JoshuaHinman submitted a review, later dismissed
all tests passed

2024-09-22 02:28 UTC, cherylli commented
@Ajen07, I'd say just go ahead and make them all in the same voyage, v52, 53 sounds good since they are coming up. I just saw the current seed has people in more than 1 team anyway

2024-09-23 12:12 UTC, cherylli requested changes

2024-09-23 17:21 UTC, Ajen07 commented on prisma/seed/voyage-teams.ts
> +    // team with only PO
Ok I will do the necessary changes

2024-09-26 03:19 UTC, JoshuaHinman submitted a review, later dismissed
All tests passed!

2024-09-30 13:01 UTC, cherylli requested changes
Please also update the wiki page with the new teams
https://github.com/chingu-x/chingu-dashboard-be/wiki/Test-Teams-and-Users

2024-09-30 13:01 UTC, cherylli commented on prisma/seed/voyage.ts
> +            endDate: new Date("2025-02-16T04:59:59.000Z"),
please update endDate, soloprojectDeadline, CertificationIssueDate and showcasePublishDat as above (v52) - you can see here for more detail (https://github.com/chingu-x/chingu-dashboard-be/wiki/Timezone)

2024-10-04 12:45 UTC, cherylli commented
update second reviewer to @curtwl as josh is away

2024-10-04 12:58 UTC, cherylli requested changes
> Please also update the wiki page with the new teams https://github.com/chingu-x/chingu-dashboard-be/wiki/Test-Teams-and-Users

Still need this updated

I fixed the voyage dates based on the voyage schedule, it is very important we have the date and exact time right as it would impact what pages/features is enabled/disabled in the frontend

2024-10-06 13:33 UTC, Ajen07 commented
> > Please also update the wiki page with the new teams https://github.com/chingu-x/chingu-dashboard-be/wiki/Test-Teams-and-Users
> 
> Still need this updated
> 
> I fixed the voyage dates based on the voyage schedule, it is very important we have the date and exact time right as it would impact what pages/features is enabled/disabled in the frontend

I have updated the wiki page

2024-10-07 02:31 UTC, cherylli approved these changes

2024-10-07 02:31 UTC, cherylli commented
Updated v53 start date as it was an invalid date.
Seeding worked fine

2024-10-10 23:43 UTC, curtwl approved these changes
lgtm

2024-10-10 23:45 UTC, merged