feat(sprints.service.spec): created unit tests for the sprints' service and controller methods
chingu-x/chingu-dashboard-be pull request #224
Opened 2024-11-21 18:45 UTC by timDeHof

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Issue link

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [x] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have updated the change log

2024-11-27 11:05 UTC, cherylli commented
All tests passed but I'm getting this, normal seeding (`prisma db seed`) is also fine
![image](https://github.com/user-attachments/assets/895f0779-ea77-41d6-b9d0-6a7a9f841ecf)

2024-11-27 13:52 UTC, timDeHof commented
> All tests passed but I'm getting this, normal seeding (`prisma db seed`) is also fine ![image](https://private-user-images.githubusercontent.com/6191116/390381954-895f0779-ea77-41d6-b9d0-6a7a9f841ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTQ4MTYsIm5iZiI6MTczMjcxNDUxNiwicGF0aCI6Ii82MTkxMTE2LzM5MDM4MTk1NC04OTVmMDc3OS1lYTc3LTQxZDYtYjlkMC02YTdhOWY4NDFlY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTMzNTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg0ZmUzNWJmN2NlOTNmM2Y2NmI4MDI4YjNmMTllZDI3N2Y3NTk3ZjI4MmI3NzU2NTUxZGVlOGJlNTUyNjk5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.z95w62KqXRf46WiJcf-s20PT5clJlc6u0OO_z0uVe8M)

I think this comes from my test in `sprints.service`, where I test for database errors during response group creation since the `addCheckinFormResponse` method would console log the error. I have added a jest's `spyOn` function to catch the errors. The Spy might fail if we change to something other than "log" like "error".

2024-11-27 14:37 UTC, Ajen07 requested changes

2024-11-27 14:37 UTC, Ajen07 commented on src/sprints/sprints.controller.spec.ts
> +  };
I think we don't  need  to use  `??` operator  as the left hand side will never be null

2024-11-29 15:38 UTC, Ajen07 submitted a review, later dismissed

2024-11-30 14:04 UTC, cherylli commented
All tests passed and worked. I'm not requesting any changes but have a few questions/comments
- "Also created centralized mock data system for improved test maintainability." Does that mean mock-data.ts is a shared file? Should we update the other tests to use this?

2024-12-01 18:26 UTC, timDeHof commented
> All tests passed and worked. I'm not requesting any changes but have a few questions/comments
> 
> * "Also created centralized mock data system for improved test maintainability." Does that mean mock-data.ts is a shared file? Should we update the other tests to use this?

Yes, My idea for `mock-data.ts` is to be shared file to generate test items.

2024-12-02 00:39 UTC, cherylli commented
> > All tests passed and worked. I'm not requesting any changes but have a few questions/comments
> > 
> > * "Also created centralized mock data system for improved test maintainability." Does that mean mock-data.ts is a shared file? Should we update the other tests to use this?
> 
> Yes, My idea for `mock-data.ts` is to be shared file to generate test items.

In this case, should we move it under some sort of shared folder instead of under /sprint module?

I will also add some low priority tasks to update old tests to use this, more importantly all new tests should use the shared mock data

2024-12-02 00:48 UTC, timDeHof commented
I'll move the file to the shared folder and let you know when its ready.

2024-12-02 01:22 UTC, timDeHof commented
I have moved the `mock-data.ts` to `/global/mocks`

2024-12-02 02:00 UTC, cherylli approved these changes
thanks, re ran all the tests with new changes, all passed

2024-12-02 02:01 UTC, cherylli commented on src/sprints/sprints.service.spec.ts
> +                    where: { id: formId },
this was from last time he didn't get sent 😂

2024-12-02 02:03 UTC, merged