Feature/test ideations api endpoints
chingu-x/chingu-dashboard-be pull request #53
Opened 2023-11-13 01:09 UTC by kennytram

# Description

Tests for ideations api endpoints

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Passed all test cases that I've created.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-13 09:47 UTC, cherylli approved these changes
All tests passed

2023-11-13 11:30 UTC, cherylli submitted a review, later dismissed

2023-11-21 01:56 UTC, smurph7894 requested changes
Have you run format before pushing for PR on this branch? Otherwise all tests for ideations are passing.

2023-11-21 02:18 UTC, kennytram commented
> [Nov 20, 2023](#event-11014933356)
> [<img alt="smurph7894" width="40" height="40" src="https://avatars.githubusercontent.com/u/104289709?s=60&amp;v=4">](/smurph7894)
> ** [smurph7894](/smurph7894) ** requested changes [ Nov 20, 2023 ](#pullrequestreview-1740974524)
> [ View reviewed changes ](/chingu-x/chingu-dashboard-be/pull/53/files/01f081188f88b313c8dc10a87d8b6f7cae3e4d1a)

It should be formatted unless I have the same problem as @cherylli used to have.

2023-11-21 02:38 UTC, smurph7894 commented
> It should be formatted unless I have the same problem as @cherylli used to have.

When testing the branch I ran yarn format to check and it made changes.

2023-11-21 02:42 UTC, kennytram commented
> > It should be formatted unless I have the same problem as @cherylli used to have.
> 
> When testing the branch I ran yarn format to check and it made changes.

Can you try staging them to see if they'll stay "staged" for commit? For now, I'll take a look at my settings.

2023-11-21 02:52 UTC, smurph7894 commented
> > > It should be formatted unless I have the same problem as @cherylli used to have.
> > 
> > 
> > When testing the branch I ran yarn format to check and it made changes.
> 
> Can you try staging them to see if they'll stay "staged" for commit? For now, I'll take a look at my settings.

Not sure what's happening. They show up as commits but won't let me stage so I think you're good.

2023-11-21 02:53 UTC, smurph7894 approved these changes
gtm

2023-11-21 04:34 UTC, cherylli approved these changes
![image](https://github.com/chingu-x/chingu-dashboard-be/assets/6191116/fd712cb5-b79c-4862-852b-85db5a0142be)
![image](https://github.com/chingu-x/chingu-dashboard-be/assets/6191116/de13709d-90c0-4d3d-90f8-186f7ab41874)

2023-11-21 04:34 UTC, cherylli commented on src/ideations/ideations.controller.spec.ts
> +        console.log(ideation);
we could remove all these console.log (probably won't bother now since it will dismiss all the approvals again) ...

2023-11-21 05:50 UTC, merged